### ISSUE TITLE
log-0.1.0 doesn't compile with GHC 7.10.1

### ISSUE THREAD

**Issue by peti** [scrive/log#1]
Citing from http://hydra.cryp.to/build/804719/log/raw:

    src/Log/Data.hs:16:10:
        No instance for (GHC.Generics.Generic LogLevel)
          arising from a use of ‘Control.DeepSeq.$gdmrnf’
        In the expression: Control.DeepSeq.$gdmrnf
        In an equation for ‘rnf’: rnf = Control.DeepSeq.$gdmrnf
        In the instance declaration for ‘NFData LogLevel’

**Comment by arybczak** [comment]
Fixed in 0.1.1.
