### ISSUE TITLE
Add to Stackage

### ISSUE THREAD

**Issue by phadej** [scrive/log#19]
That would be cool!

now as bloodhound is there again too.

**Comment by 23Skidoo** [comment]
Are you willing to oversee this process? Then I can probably add you as a co-maintainer.

BTW, I'm working on #14 right now, so it makes sense to wait until that is finished.

**Comment by phadej** [comment]
The #14 is great news. I'm moving to `log` at work, so yes, I guess I'll have enough motivation to look after bounds issues..

**Comment by 23Skidoo** [comment]
Cool, I'll assign this to you then.

**Comment by 23Skidoo** [comment]
@phadej Gave you write access.

**Comment by phadej** [comment]
Done: https://www.stackage.org/nightly-2016-11-26/package/log-base-0.7

**Comment by 23Skidoo** [comment]
Great, thanks!
