### ISSUE TITLE
Ideas / Opinions for expanding LogLevel

### ISSUE THREAD

**Issue by jonathanjouty** [scrive/log#31]
Currently we have `data LogLevel = LogAttention | LogInfo | LogTrace`.

My questions are:
1. Whether anyone feels that more levels are necessary? (or put another way, whether anyone is against adding more levels)
2. If so, what should they be? If not, why?

cc/ @23Skidoo @phadej @arybczak

**Comment by 23Skidoo** [comment]
In Cabal we have four "log levels", `debug`, `info`, `notice` and `warn`. `notice` and `warn` are shown by default, `info` only at `-v2`, `debug` only at `-v3`.

**Comment by arybczak** [comment]
@jonathanjouty what are your answers to these questions? :)

The main advantage of the current log levels is that they are pretty much self-explanatory, i.e. when you want to log a message, you don't have to wonder what level should it really belong to.

**Comment by jonathanjouty** [comment]
@arybczak :)
What is lacking for me is a level between `LogInfo` and `LogAttention`.

This may be as currently at Scrive we use `LogInfo` for all kind of standard things (as you will know) and `LogAttention` when anything goes wrong.
What's missing for me is distinguishing between "something went wrong, but it's not so bad" and "something really went wrong". The latter could be used for monitoring and alerting systems, whereas the former is useful for analysis and catching trends before they really become a problem.

For me, `LogTrace` is similar to `debug`, and the idea is for it to be turned off in "production mode", although, from what I can tell, the `log` package does not actually provide for minimum logging levels?
So in a way maybe a solution to my problem is simply to start using `LogTrace`...

**Comment by mariuszrak** [comment]
Please, please, please don't introduce more log levels. We had that earlier and it's close to impossible to have more then two log levels used consistently for long period of time (in my opinion) :(

**Comment by phadej** [comment]
I'm pretty happy with three levels, I don't need distinction between "something went wrong, but it's not bad" and "something really went wrong".  FWIW if one has "monitoring and alerting system with built-in analysis" any anomaly (e.g. too much of *any* same-log-level similar-messages) would trigger an alert.

@mariuszrak you can write `Logger` which e.g. doesn't care about trace messages, but there isn't one provided.

**Comment by jonathanjouty** [comment]
Consensus seems to be on keeping log levels as they are.
Thanks for the discussion.
